Moved scripts.

diff --git a/bin/git-export b/bin/git-export
--- a/bin/git-export
+++ b/bin/git-export
@@ -1,16 +1,24 @@
 #!/bin/sh
 
 DATE=$(date +"%Y-%m-%d--%H-%M-%S")
-REPO=$(awk -F/ '{ print $NF}' <<<"$(git rev-parse --show-toplevel)")
-BRANCH=$(git branch | awk '$1 == "*" { print $2 }')
 SEP="\033[35m>>>\033[0m"
 
-echo "\n\033[35m*\033[0m \033[36mExporting repo\033[0m \033[33m$REPO\033[0m \033[35m*\033[0m"
+echo "\n\033[35m*\033[0m \033[31mExporting repo\033[0m \033[33m$REPO\033[0m \033[35m*\033[0m"
+if git rev-parse --git-dir > /dev/null 2>&1 || -d .git;
+then
+    REPO=$(awk -F/ '{ print $NF}' <<<"$(git rev-parse --show-toplevel)")
+    BRANCH=$(git branch | awk '$1 == "*" { print $2 }')
+    echo $SEP "Git repository found: \033[33m<$REPO>\033[0m on branch \033[33m<$BRANCH>\033[0m."
+else
+    echo $SEP "\033[31mNo Git repository to export, aborting ...\033[0m"
+    exit 1
+fi
+
 while getopts "b:o:" opt;
 do
   case $opt in
     b)
-        if [ git branch | grep $OPTARG > /dev/null ];
+        if git branch | grep $OPTARG > /dev/null;
         then
             BRANCH=$OPTARG
             echo $SEP "Setting branch to \033[36m<$BRANCH>\033[0m."
@@ -28,8 +36,8 @@ do
 done
 
 FILENAME=$REPO-$DATE-$BRANCH.zip
-
-echo $SEP "Exporting branch \033[36m<$BRANCH>\033[0m to \033[36m$FILENAME\033[0m ..."
+echo $SEP "Exporting branch \033[36m<$BRANCH>\033[0m to \033[36m$FILENAME\033[0m."
+echo $SEP "Please wait ..."
 git archive --format zip --output $FILENAME $BRANCH
 wait
 echo $SEP "Done.\n\n"
